#ifndef WR_CONFIG_H
#define WR_CONFIG_H

#ifndef CONFIG_OPUS_MODE_CELT
#define CONFIG_OPUS_MODE_CELT (1 << 0)
#endif
#ifndef CONFIG_OPUS_MODE_SILK
#define CONFIG_OPUS_MODE_SILK (1 << 1)
#endif
#ifndef CONFIG_OPUS_MODE_HYBRID
#define CONFIG_OPUS_MODE_HYBRID (CONFIG_OPUS_MODE_CELT | CONFIG_OPUS_MODE_SILK)
#endif

#define CODEC_OPUS 1
#define CODEC_PACKAGE_SAMPLES 160
#define CODEC_OUTPUT_MAX_BYTES (CODEC_PACKAGE_SAMPLES * 2)
#define CODEC_OPUS_BITRATE 32000
#define CODEC_OPUS_VBR 1
#define CODEC_OPUS_COMPLEXITY 3
#define CONFIG_OPUS_MODE CONFIG_OPUS_MODE_CELT

#endif /* WR_CONFIG_H */
